/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg00390aw;

import java.io.File;
import java.io.IOException;
import java.util.Calendar;
import java.util.LinkedList;
import java.util.Queue;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author WINDOWS 10
 */
public class FrameReservas extends javax.swing.JFrame {

    /**
     * Creates new form FrameReservas
     */
    public FrameReservas() throws IOException, ClassNotFoundException {
        initComponents();
        this.pantFechaActual.setText(fecha());
        this.setLocationRelativeTo(null);
        lr = new ListaReservas();
        File f = new File("ListaReservas.dat");
        if (f.exists()) {
            this.lr = lr.recuperar();
            mostrarEnTabla();
        }
    }

    private ListaReservas lr;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        pantNombre = new javax.swing.JTextField();
        pantFechaActual = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        pantHora = new javax.swing.JSpinner();
        pantMinuto = new javax.swing.JSpinner();
        pantNroPersonas = new javax.swing.JSpinner();
        pantLugar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        pantFechaReservacion = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("RESERVACIONES");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 107, 35));

        jLabel2.setText("NOMBRE:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 50, -1, -1));

        jLabel3.setText("FECHA ACTUAL:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, -1, -1));

        jLabel4.setText("FECHA DE RESERVACION");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, -1, -1));

        jLabel5.setText("HORA");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 50, -1, -1));

        jLabel6.setText("Nro. De personas");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 50, -1, -1));

        jLabel7.setText("LUGAR");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 50, -1, -1));
        getContentPane().add(pantNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 160, -1));
        getContentPane().add(pantFechaActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 110, -1));

        jLabel8.setText("MINUTO");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 50, -1, -1));
        getContentPane().add(pantHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 70, 50, -1));
        getContentPane().add(pantMinuto, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 70, 50, -1));
        getContentPane().add(pantNroPersonas, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 70, 60, -1));
        getContentPane().add(pantLugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 70, 60, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {}
            },
            new String [] {
                "Nombre", "Nro. Personas", "Fecha Actual", "Fecha de Reservacion","Hora","Lugar"
                + ""
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 760, 150));

        jButton1.setText("GUARDAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 170, 50));
        getContentPane().add(pantFechaReservacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, 130, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        guardarDatos();
        mostrarEnTabla();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    public void guardarDatos() {
        Reservas r = new Reservas();
        r.setNombre(this.pantNombre.getText());
        r.setNroPersonas((int) this.pantNroPersonas.getValue());
        r.setFechaActual(this.pantFechaActual.getText());
        Calendar c=this.pantFechaReservacion.getCalendar();
        String dia=c.get(Calendar.DAY_OF_MONTH)+"";
        String mes=(c.get(Calendar.MONTH)+1)+"";
        String anio=c.get(Calendar.YEAR)+"";
        String fecha1=dia+"/"+mes+"/"+anio;
        c.add(Calendar.DAY_OF_MONTH, 1);
        dia=c.get(Calendar.DAY_OF_MONTH)+"";
        mes=(c.get(Calendar.MONTH)+1)+"";
        anio=c.get(Calendar.YEAR)+"";
        String fecha2=dia+"/"+mes+"/"+anio;
        r.setFechaReservacion(fecha1);
        r.setHora((int) this.pantHora.getValue());
        r.setMinuto((int) this.pantMinuto.getValue());
        r.setLugar(this.pantLugar.getText());
        this.lr.getReservas().add(r);
        this.lr.guardad(lr);
    }
    public String fecha() {
        String f = "";
        int dia, mes, anio;
        Calendar calendario = Calendar.getInstance();
        dia = calendario.get(Calendar.DAY_OF_MONTH);
        mes = calendario.get(Calendar.MONTH) + 1;
        anio = calendario.get(Calendar.YEAR);
        f = dia + "/" + mes + "/" + anio;
        return f;
    }

    public void reiniciarTabla() {
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "Nombre", "Nro. Personas", "Fecha Actual", "Fecha de Reservacion", "Hora", "Lugar"
                    + ""
                }
        ));
    }

    public void agregarFilaATabla1() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{});
    }

    public void mostrarEnTabla() {
        reiniciarTabla();
        Queue<Reservas> aux = new LinkedList();
        aux.addAll(lr.getReservas());
        int fila = 0;
        while (!aux.isEmpty()) {
            agregarFilaATabla1();
            Reservas r = aux.remove();
            this.jTable1.setValueAt(r.getNombre(), fila, 0);
            this.jTable1.setValueAt(r.getNroPersonas(), fila, 1);
            this.jTable1.setValueAt(r.getFechaActual(), fila, 2);
            this.jTable1.setValueAt(r.getFechaReservacion(), fila, 3);
            this.jTable1.setValueAt(r.getHora() + ":" + r.getMinuto(), fila, 4);
            this.jTable1.setValueAt(r.getLugar(), fila, 5);
            fila++;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameReservas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameReservas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameReservas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameReservas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new FrameReservas().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(FrameReservas.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(FrameReservas.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField pantFechaActual;
    private com.toedter.calendar.JDateChooser pantFechaReservacion;
    private javax.swing.JSpinner pantHora;
    private javax.swing.JTextField pantLugar;
    private javax.swing.JSpinner pantMinuto;
    private javax.swing.JTextField pantNombre;
    private javax.swing.JSpinner pantNroPersonas;
    // End of variables declaration//GEN-END:variables
}
